export const ADD_NEW_EMPLOYEE_REQUEST = 'ADD_NEW_EMPLOYEE_REQUEST'
export const ADD_NEW_EMPLOYEE_SUCCESS = 'ADD_NEW_EMPLOYEE_SUCCESS'
export const ADD_NEW_EMPLOYEE_FAIL = 'ADD_NEW_EMPLOYEE_FAIL'


export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST'
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS'
export const FETCH_EMPLOYEE_FAIL = 'FETCH_EMPLOYEE_FAIL'

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL'



export const MANAGER_ORDERS_REQUEST = 'MANAGER_ORDERS_REQUEST'
export const MANAGER_ORDERS_SUCCESS = 'MANAGER_ORDERS_SUCCESS'
export const MANAGER_ORDERS_FAIL = 'MANAGER_ORDERS_FAIL'