export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL'

export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL'


export const ASSIGN_DELIVERYBOY_REQUEST = 'ASSIGN_DELIVERYBOY_REQUEST'
export const ASSIGN_DELIVERYBOY_SUCCESS = 'ASSIGN_DELIVERYBOY_SUCCESS'
export const ASSIGN_DELIVERYBOY_FAIL = 'ASSIGN_DELIVERYBOY_FAIL'